import { StyleSheet, Dimensions } from 'react-native';

export const styles = StyleSheet.create({
  rootWrapper: {
    flex: 1,
  },
  container: {
    flex: 1,
  },
  outputArea: {
    padding: 16,
    margin: 12,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  selectedWordsWrapper: {
    minHeight: 90, // CRITICAL: Fixed minimum height to avoid layout shift
    justifyContent: 'center',
  },
  selectedWordsScrollView: {
    maxHeight: 90,
  },
  selectedWordsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: 12,
    paddingVertical: 4,
  },
  selectedWordItem: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 70,
    marginRight: 12,
    padding: 6,
    borderRadius: 12,
    borderWidth: 3,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  selectedWordImage: {
    width: 50,
    height: 50,
    marginBottom: 4,
  },
  selectedWordText: {
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  emptySelectionText: {
    fontSize: 14,
    fontStyle: 'italic',
    textAlign: 'center',
    paddingVertical: 8,
  },
  section: {
    marginHorizontal: 12,
    marginBottom: 12,
    flex: 1,
    minHeight: 0, // Important for ScrollView to work inside flex
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  categoryGridContainer: {
    width: Dimensions.get('window').width - 24, // Screen width minus section margins (12*2)
    paddingHorizontal: 8,
    flex: 1,
  },
  categoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  categoryEmoji: {
    fontSize: 24,
    marginRight: 8,
  },
  categoryName: {
    fontSize: 20,
    fontWeight: '700',
  },
  categoryScrollView: {
    flex: 1,
    minHeight: 0, // Important for ScrollView to work inside flex
  },
  grid3x3Container: {
    paddingBottom: 10,
  },
  grid3x3: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  symbolButton: {
    width: '30%', // 3 columns with spacing between them (100% / 3 - spacing)
    aspectRatio: 1,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 2,
    marginBottom: 10,
  },
  emptyCategoryContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
  },
  emptyCategoryText: {
    fontSize: 16,
    fontStyle: 'italic',
    textAlign: 'center',
  },
  symbolImage: {
    width: 70,
    height: 70,
    marginBottom: 6,
  },
  symbolText: {
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  actionButtons: {
    padding: 16,
    paddingHorizontal: 40,
    paddingTop: 0,
    paddingBottom: 0,
    marginTop: 0,
    flexDirection: 'row',
    gap: 16,
    flexShrink: 0,
  },
  pcsButton: {
    flex: 1,
    aspectRatio: 1.2,
    minHeight: 120,
    maxHeight: 120,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
    borderWidth: 3,
    padding: 8,
    paddingHorizontal: 12,
  },
  pcsButtonImage: {
    width: 60,
    height: 60,
    marginBottom: 6,
  },
  pcsButtonText: {
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  errorContainer: {
    backgroundColor: '#f0f0f0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorText: {
    fontSize: 30,
  },
  errorSubtext: {
    fontSize: 10,
    marginTop: 4,
  },
  loadingMoreContainer: {
    width: '100%',
    paddingVertical: 20,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  loadingMoreText: {
    fontSize: 14,
    fontStyle: 'italic',
  },
  loadMoreButton: {
    width: '100%',
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    borderWidth: 2,
  },
  loadMoreButtonIcon: {
    fontSize: 20,
    marginRight: 4,
  },
  loadMoreButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: 'white',
  },
  dotsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 12,
    paddingTop: 25,
    gap: 8,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  categoryNavigationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingTop: 10,
    paddingBottom: 0,
    gap: 4,
  },
  navButtonWrapper: {
    width: 46,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navButtonIndicator: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
    flexShrink: 0,
  },
  navButtonArrow: {
    width: 24,
    height: 24,
  },
  categoryIndicatorsContainer: {
    flex: 1,
    paddingVertical: 2,
    maxHeight: 75,
    minHeight: 55,
    marginHorizontal: 4,
    maxWidth: Dimensions.get('window').width - 104, // Screen width minus arrow space (40*2 + padding)
  },
  categoryIndicatorsScrollContent: {
    paddingHorizontal: 8, // Padding to prevent first button from being cut when scaling
    gap: 4,
    alignItems: 'center',
    paddingVertical: 2,
  },
  categoryIndicator: {
    minWidth: 56,
    paddingHorizontal: 5,
    paddingVertical: 7,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  categoryIndicatorEmoji: {
    fontSize: 16,
    marginBottom: 2,
  },
  categoryIndicatorName: {
    fontSize: 10,
    textAlign: 'center',
  },
});

